
-- Business Question:
-- What is the total revenue generated by the business?
SELECT SUM(amount) as total_revenue from payment;

-- What is the monthly revenue trend?
SELECT 
    DATE_FORMAT(payment_date, '%Y-%m') AS month,
    SUM(amount) AS monthly_revenue
FROM payment
GROUP BY month
ORDER BY month;

-- Which store generates the highest revenue?
SELECT 
    s.store_id,
    SUM(p.amount) AS highest_revenue
FROM store s
JOIN staff st 
    ON st.store_id = s.store_id
JOIN payment p 
    ON p.staff_id = st.staff_id
GROUP BY s.store_id
ORDER BY highest_revenue DESC
LIMIT 1;

-- Which film categories contribute the most revenue?
SELECT 
    c.name AS category,
    SUM(p.amount) AS total_revenue
FROM payment p
JOIN rental r 
    ON r.rental_id = p.rental_id
JOIN inventory i 
    ON i.inventory_id = r.inventory_id
JOIN film f 
    ON f.film_id = i.film_id
JOIN film_category fc 
    ON fc.film_id = f.film_id
JOIN category c 
    ON c.category_id = fc.category_id
GROUP BY c.name
ORDER BY total_revenue DESC
LIMIT 5;

-- Which movies generate the highest rental revenue?
SELECT 
    f.title,
    SUM(p.amount) AS rental_revenue
FROM payment p
JOIN rental r 
    ON r.rental_id = p.rental_id
JOIN inventory i 
    ON i.inventory_id = r.inventory_id
JOIN film f 
    ON f.film_id = i.film_id
GROUP BY f.title
ORDER BY rental_revenue DESC
LIMIT 10;
